# Assignment on Statistics

1.Importing all Libraries and loading the dataset

In [98]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stats

In [99]:
data1 = pd.read_csv("Students_Performance.csv")

In [100]:
data1.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some high school,free/reduced,none,0,17,10
1,female,group B,high school,free/reduced,none,8,24,23
2,female,group B,some high school,free/reduced,none,18,32,28
3,female,group B,some college,standard,none,11,38,32
4,female,group C,some college,free/reduced,none,22,39,33
5,female,group B,high school,free/reduced,completed,23,44,36
6,female,group B,some high school,free/reduced,none,24,38,27
7,female,group D,associate's degree,free/reduced,none,26,31,38
8,female,group D,some high school,free/reduced,none,19,34,32
9,female,group C,high school,standard,none,29,29,30

In [101]:
data1.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group C,associate's degree,standard,none,97,93,91
991,male,group E,some college,standard,none,97,87,82
992,male,group E,associate's degree,standard,completed,97,82,88
993,male,group C,some college,standard,completed,98,86,90
994,male,group C,associate's degree,standard,completed,98,87,90
995,male,group E,some college,standard,completed,99,87,81
996,male,group A,some college,standard,completed,100,96,86
997,male,group D,some college,standard,completed,100,97,99
998,male,group E,associate's degree,free/reduced,completed,100,100,93
999,male,group E,bachelor's degree,standard,completed,100,100,100

In [102]:

data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [103]:
data1.describe()

        math score  reading score  writing score
count  1000.000000    1000.000000    1000.000000
mean     66.001000      69.195000      68.119000
std      15.569567      14.706436      15.226381
min       0.000000      17.000000      10.000000
25%      57.000000      59.000000      58.000000
50%      66.000000      70.000000      69.000000
75%      77.000000      79.250000      79.000000
max     100.000000     100.000000     100.000000



a. Find out how many males and females participated in
the test.

In [104]:
gender_total = data1['gender'].value_counts()
print(gender_total)

female    518
male      482
Name: gender, dtype: int64

b. What do you think about the students' parental level of
education?

In [105]:
parential_counts = data1['parental level of education'].value_counts()
print(parential_counts)

some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: parental level of education, dtype: int64

c. Who scores the most on average for math, reading and
writing based on


i. Gender

In [106]:
averagescore_gender = data1.groupby('gender').mean()[['math score', 'reading score', 'writing score']]
print(averagescore_gender)

        math score  reading score  writing score
gender
female   63.376448      72.590734      72.467181
male     68.821577      65.545643      63.446058

<ipython-input-106-33f979c461c9>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  averagescore_gender = data1.groupby('gender').mean()[['math score', 'reading score', 'writing score']]

In [107]:

best_math_gender = averagescore_gender['math score'].idxmax()

In [108]:
print(best_math_gender)

male

In [109]:
best_reading_gender = averagescore_gender['reading score'].idxmax()
print(best_reading_gender)

female

In [110]:
best_writing_gender = averagescore_gender['writing score'].idxmax()
print(best_writing_gender)

female

Who scores the most on average for math, reading and
writing based on



ii. Test preparation course

In [111]:
averagescore_testprep = data1.groupby('test preparation course').mean()[['math score', 'reading score', 'writing score']]
print(averagescore_testprep)

                         math score  reading score  writing score
test preparation course
completed                  69.96648      74.175978      74.684358
none                       63.78972      66.417445      64.457944

<ipython-input-111-99ec53131779>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  averagescore_testprep = data1.groupby('test preparation course').mean()[['math score', 'reading score', 'writing score']]

d. What do you think about the scoring variation for
math, reading and writing based on


i. Gender

In [112]:
stddev_gender = data1.groupby('gender').std()[['math score', 'reading score', 'writing score']]
print(stddev_gender)

        math score  reading score  writing score
gender
female   16.029928      14.411018      14.844842
male     14.556411      14.149594      14.227225

<ipython-input-112-c9eb1de87240>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  stddev_gender = data1.groupby('gender').std()[['math score', 'reading score', 'writing score']]

d. What do you think about the scoring variation for
math, reading and writing based on


ii. Test preparation course

In [113]:
stddev_testprep = data1.groupby('test preparation course').std()[['math score', 'reading score', 'writing score']]
print(stddev_testprep)

                         math score  reading score  writing score
test preparation course
completed                 14.521847      13.537572      13.236412
none                      15.705689      14.608896      15.041667

<ipython-input-113-f4f76e2b60da>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  stddev_testprep = data1.groupby('test preparation course').std()[['math score', 'reading score', 'writing score']]

e. The management needs your help to give bonus points
to the top 25% of students based on their math score,
so how will you help the management to achieve this.

In [114]:
math_scores = data1['math score']
q1 = np.percentile(math_scores, 25)

In [115]:
top_25_percent = data1[data1['math score'] >= q1]
print(top_25_percent)

     gender race/ethnicity parental level of education         lunch  \
153  female        group B          associate's degree      standard
154  female        group B            some high school      standard
155  female        group C          associate's degree  free/reduced
156  female        group C          associate's degree      standard
157  female        group D          associate's degree  free/reduced
..      ...            ...                         ...           ...
995    male        group E                some college      standard
996    male        group A                some college      standard
997    male        group D                some college      standard
998    male        group E          associate's degree  free/reduced
999    male        group E           bachelor's degree      standard

    test preparation course  math score  reading score  writing score
153                    none          57             69             68
154                    none          57             67             72
155                    none          57             78             67
156               completed          57             77             80
157               completed          57             74             76
..                      ...         ...            ...            ...
995               completed          99             87             81
996               completed         100             96             86
997               completed         100             97             99
998               completed         100            100             93
999               completed         100            100            100

[753 rows x 8 columns]

# Case Study on Testing of Hypothesis

# Loading the dataset

In [116]:
data2 = pd.read_csv("Sales_add.csv")

In [117]:
data2.head()

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
0,Month-1,Region - A,Manager - A,132921,270390
1,Month-2,Region - A,Manager - C,149559,223334
2,Month-3,Region - B,Manager - A,146278,244243
3,Month-4,Region - B,Manager - B,152167,231808
4,Month-5,Region - C,Manager - B,159525,258402

In [118]:
data2.tail()

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
17,Month-18,Region - C,Manager - B,167996,191517
18,Month-19,Region - B,Manager - A,132135,227040
19,Month-20,Region - A,Manager - B,152493,212579
20,Month-21,Region - B,Manager - A,147425,263388
21,Month-22,Region - A,Manager - C,130263,243020

In [119]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64
 4   Sales_After_digital_add(in $)   22 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes

In [120]:
data2.describe()

       Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

a. The company wishes to clarify whether there is any
increase in sales after stepping into digital marketing


T Test
H0:  no significant difference
H1: significant increase.

In [121]:

before = data2['Sales_before_digital_add(in $)']
after = data2['Sales_After_digital_add(in $)']

In [122]:
from scipy.stats import ttest_ind
before = data2['Sales_before_digital_add(in $)']
after = data2['Sales_After_digital_add(in $)']
t_stat1,p_value=ttest_ind(before,after)
print (t_stat1)
print(p_value)

-12.995084451110875
2.614368006904645e-16

In [123]:
if p_value <0.05:
    print("Reject the null hypothesis: There is a significant increase in sales.")
else:
    print("Fail to reject the null hypothesis: No significant increase in sales.")

Reject the null hypothesis: There is a significant increase in sales.

b. The company needs to check whether there is any
dependency between the features “Region” and
“Manager”.


CHiSquare test

H0 : Region and Manager  are independent
H1:Region and Manager  are dependent.

In [135]:
from scipy.stats import chisquare
from scipy.stats import chi2_contingency

In [132]:
observed = pd.crosstab(data2['Region'],data2['Manager'])

In [133]:
print(observed)

Manager     Manager - A  Manager - B  Manager - C
Region
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [138]:

chi2_stat, p_value1, dof,exp = chi2_contingency(observed)
print(chi2_stat)
print(p_value1)

3.050566893424036
0.5493991051158094

In [140]:
if p_value1 < 0.05:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis